stages:
  train:
    cmd: python src/train.py data/data.csv model/model.pkl
    deps:
      - data/data.csv
    outs:
      - model/model.pkl
  evaluate:
    cmd: python src/evaluate.py model/model.pkl data/data.csv metrics/eval.json
    deps:
      - data/data.csv
      - model/model.pkl
    outs:
      - metrics/eval.json